# Site settings
title: Nikul Lakhani's Blog
description: I love creating creative and clean design for the web. I would design the "Design" in a simple sense as my passion.'
email: mr.niklakhani@gmail.com
author: "Nikul Lakhani"
username: "niklakhani"
baseurl: ""
url: "https://niklakhani.in"
port: 8080

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
sass:
  sass_dir: assets/css/
  style: compressed
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

# Google author/publisher settings
google-author: 'https://plus.google.com/+NIKLAKHANI009/'
google-publisher: 'https://plus.google.com/+NIKLAKHANI009/'

# Skills
skills:
- {name: Creative, fill: 7}
- {name: Responsible, fill: 8}
- {name: Multitasking, fill: 8}
- {name: Communication, fill: 6}
- {name: Performance Tuning, fill: 6}
- {name: WordPress, fill: 7}
- {name: Design, fill: 7}
- {name: Development, fill: 8}